version: '3.8'

services:
  inventory-service:
    build: .
    container_name: inventory-management
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:inventory_db
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - inventory-network

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"
networks:
  inventory-network:
    driver: bridge