version: '3.8'

services:
  inventory-service:
    build: .
    container_name: inventory-management
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:inventory_db
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    restart: unless-stopped
    networks:
      - inventory-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # APLICACAO
      - "15672:15672" # PAINEL

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"
networks:
  inventory-network:
    driver: bridge