services:
  inventory-service:
    build: .
    container_name: inventory-management
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis
      - db_inventory

  db_inventory:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: "redis"
    ports:
      - "6379:6379"