openapi: 3.0.3
info:
  title: Sistema de Estoque Distribuido
  description: API para gerenciamento de estoque.
  version: 1.0.0
  contact:
    name: Jobisvaldo Silva
    email: contato@estoque.com
    url: https://sistema-de-estoque.com.br

servers:
  - url: '{protocol}:{url-base}/api/v1'
    variables:
      url-base:
        enum:
          -  //localhost:8080
        default: //localhost:8080
      protocol:
        enum:
          - http
          - https
        default: https
    description: Servidor de Desenvolvimento

paths:
  /products:
    get:
      tags:
        - products
      operationId: getProducts
      summary: Lista todos os produtos
      description: Retorna uma lista paginada de todos os produtos
      parameters:
        - name: page
          in: query
          description: Número da página (começa em 0)
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Tamanho da página
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Lista de produtos retornada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPage'
    post:
      operationId: create
      tags:
        - products
      summary: Cria um novo produto
      description: Cria um novo produto no sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Dados inválidos fornecidos
components:

  schemas:
    CreateProductRequest:
      type: object
      properties:
        sku:
          type: string
          example: "SKU-001"
          minLength: 4
          maxLength: 12
        name:
          type: string
          example: "Camiseta Básica"
        description:
          type: string
          example: "Camiseta 100% algodão"
        price:
          type: number
          format: double
          example: 59.90
        quantity:
          type: integer
          example: 100
        category:
          type: string
          example: "Vestuário"

    ProductResponse:
      type: object
      properties:
        id:
          type: string
          example: p-001
        name:
          type: string
          example: "Camiseta Básica"
        description:
          type: string
          example: "Camiseta 100% algodão"
        price:
          type: number
          format: double
          example: 59.90
        category:
          type: string
          example: "Vestuário"
        quantity:
          type: integer
          example: 100

    ProductPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'
        pageable:
          type: object
          properties:
            pageNumber:
              type: integer
              example: 0
            pageSize:
              type: integer
              example: 20
            totalElements:
              type: integer
              example: 100
            totalPages:
              type: integer
              example: 5
            last:
              type: boolean
              example: false